[tool.ruff]
target-version = "py37"
ignore = [
    "B028", # warning without explicit stacklevel
    "E501",
]
extend-select = ["E", "F", "I", "W", "UP", "B"]
line-length = 119

[tool.ruff.isort]
lines-after-imports = 2
known-first-party = ["trl"]
